name: Dispatcher workflow suite

on:
  workflow_call:
    inputs:
      resource:  
        required: false
        type: string

jobs:
  use-file:
    name: Use file
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: /tmp/files
          key: layer-cache
      - run: ls -la
      - run: |
          mkdir -p ./opt/{lib}
          cp /tmp/files/*.yml ./opt/lib
      - run: ls -la ./opt/lib
      - name: 🖥️  Building docker image
        run: |             
          docker build -t sample:latest .
          echo "Build docker image part finished successfully 👍 "
    