name: Dispatcher workflow suite

on:
  workflow_call:
    inputs:
      resource:  
        required: false
        type: string

jobs:
  deploy-layer:
    name: Deploy lambda using cache
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.resource, 'layer') == 'false' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
     - run: echo deploy layer to AWS
  deploy-lambda:
    name: Deploy lambda using cache
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.resource, 'layer') == 'false' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for get Repository
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml 
       
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: /tmp/files
          key: layer-cache
      - run: ls -la
      - run: |
          mkdir -p ./opt
          cd ./opt
          mkdir lib
          cd ..
          ls -la /tmp/files
          cp /tmp/files/*.* ./opt/lib/
      - run: ls -la ./opt/lib/
      - name: 🖥️  Building docker image
        run: |             
          docker build -t sample:latest .
          echo "Build docker image part finished successfully 👍 "
    