name: File changes
on:
   push:
      branches:
        - main
jobs:
  activate-workflow-layer:
    name: Detect layer changes
    runs-on: ubuntu-latest
    outputs:
        layer_changes: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
    steps: 
      - uses: actions/checkout@v3   
      - name: Run changed-files with dir_names for layers
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          base_sha: ${{ github.base_ref }}
          json_raw_format: true
          files_ignore: .github
          files: layer*         
      - name: List all changed files
        run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
  activate-workflow-lambda:
    runs-on: ubuntu-latest
    outputs:
      lambda_changes: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
    steps: 
      - uses: actions/checkout@v3   
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          base_sha: ${{ github.base_ref }}
          json_raw_format: true
          files_ignore: |
                .github
                layer*
      - name: List all changed files
        run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}  
  
  check-all-changes:
    name: check changes in specific folder
    needs: [activate-workflow-layer, activate-workflow-lambda]
    runs-on: ubuntu-latest
    outputs:
      deploy_flow: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
    steps:
      - name: Check if changes in layer or lambda
        id: changed-files-dir-names
        run: |
          if ${{ needs.activate-workflow-layer.outputs.layer_changes != '[]' && needs.activate-workflow-lambda.outputs.lambda_changes != '[]'}} 
          then
           echo "deploy_flow=all" >> $GITHUB_OUTPUT 
          fi
          if ${{ needs.activate-workflow-layer.outputs.layer_changes != '[]' && needs.activate-workflow-lambda.outputs.lambda_changes == '[]'}} 
          then
           echo "deploy_flow=layer" >> $GITHUB_OUTPUT 
          fi
          if ${{ needs.activate-workflow-layer.outputs.layer_changes == '[]' && needs.activate-workflow-lambda.outputs.lambda_changes != '[]'}} 
          then
           echo "deploy_flow=lambda" >> $GITHUB_OUTPUT 
          fi
          if ${{ needs.activate-workflow-layer.outputs.layer_changes == '[]' && needs.activate-workflow-lambda.outputs.lambda_changes == '[]'}} 
          then
           echo "deploy_flow=none" >> $GITHUB_OUTPUT 
          fi
        shell: bash 
  validate-flow:
    name: check changes in specific folder
    needs: check-all-changes
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.check-all-changes.outputs.deploy_flow}}
     