name: File changes
on:
   push:
      branches:
        - main
jobs:
  create-file:
    name: Create file
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/cache@v3
         id: restore-build
         with:
           path: ./layer
           key: ${{ github.sha }}
       - run: |
          curl https://examples.onelinerhub.com/file.zip -o tmp.zip && unzip tmp.zip && rm tmp.zip    
       - run: ls -la
      
  call-workflow:
    name: call workflow
    needs: create-file
    uses: ./.github/workflows/reusable-workflow.yml
    
   