name: File changes
on:
   push:
      branches:
        - main
env:
  LAYER_GLOBAL: 0 
jobs:
  activate-workflow-layer:
    name: Detect layer changes
    runs-on: ubuntu-latest
    outputs:
        layer_changes: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
        LAYER_COUNT: ${{ steps.layer-count.outputs.LAYER_COUNT }}
    steps: 
      - uses: actions/checkout@v3   
      - name: Run changed-files with dir_names for layers
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          base_sha: ${{ github.base_ref }}
          json_raw_format: true
          files_ignore: .github
          files: layer*         
      - name: List all changed files
        id: layer-count
        run: |
           i=0
           for file in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
              ((i=i+1))
           done 
           echo i: $i
           echo "LAYER_COUNT=$i" >> $GITHUB_OUTPUT
           echo "LAYER_GLOBAL=$i" >> $GITHUB_ENV
           echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
            
  summary:
    name: Job Summary
    runs-on: ubuntu-latest
    needs: [activate-workflow-layer]
    if: always()
    steps:
      - name: Generate list using Markdown
        run: |
          echo '### Deployment complete! :rocket: ' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          cacheKeysForPR=${{ fromJSON(needs.activate-workflow-layer.outputs.layer_changes) }}

          echo "Listing values...${#cacheKeysForPR[@]}"
          echo "Items: ${cacheKeysForPR[*]}"
          for cacheKey in $cacheKeysForPR
          do
           echo "- Number of layer deployed $cacheKeysForPR " >> $GITHUB_STEP_SUMMARY
          done
          echo "Done"

          echo "- Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY  

     